mips: MIPS.cpp
	g++ MIPS.cpp -o MIPS 
	g++ MIPS.cpp -o myCode/MIPS -D MYCODE

clean:
	rm -rf dmemresult.txt
	rm -rf RFresult.txt
	rm -rf MIPS
	rm -rf myCode/RF_result.txt
	rm -rf myCode/Dmem_result.txt
	rm -rf myCode/MIPS
