cachesimulator: cachesimulator.cpp
	g++ cachesimulator.cpp -o cachesimulator
	echo "see howto.txt"
	sh run
clean:
	rm -rf trace.txt.out
	rm -rf cachesimulator
	rm -rf check.csv
	rm -rf trace_resolved.txt
