mips: MIPS.cpp
	g++ MIPS.cpp -o MIPS 
	g++ MIPS.cpp -o myCode/MIPS -D MYCODE
	echo "see howto.txt"

clean:
	rm -rf dmemresult.txt
	rm -rf RFresult.txt
	rm -rf MIPS
	rm -rf myCode/RF_result_bubblesort.txt
	rm -rf myCode/Dmem_result_bubblesort.txt
	rm -rf myCode/MIPS
	rm -rf RF_result_bubblesort.txt
	rm -rf Dmem_result_bubblesort.txt

